# This is a basic workflow to help you get started with Actions

name: chong

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      # Runs a set of commands using the runners shell
      - name: Build Web
        run: |
          hugo
          pwd
          ls -al

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "public/"
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: 49.232.6.154
          REMOTE_USER: github
          TARGET: /var/www/html/
          SCRIPT_BEFORE: |
            whoami
            ls -al
            pwd
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
